sigcopeinca/config/routes.rb
Rails.application.routes.draw do
  resources :despachos

  resources :editals

  resources :alunos

  resources :servidors

end

sigcopeinca/app/models/edital.rb
class Edital < ActiveRecord::Base
end

sigcopeinca/app/controllers/editals_controller.rb
class EditalsController < ApplicationController
  before_action :set_edital, only: [:show, :edit, :update, :destroy]

  # GET /editals
  # GET /editals.json
  def index
    @editals = Edital.all
  end

  # GET /editals/1
  # GET /editals/1.json
  def show
  end

  # GET /editals/new
  def new
    @edital = Edital.new
  end

  # GET /editals/1/edit
  def edit
  end

  # POST /editals
  # POST /editals.json
  def create
    @edital = Edital.new(edital_params)

    respond_to do |format|
      if @edital.save
        format.html { redirect_to @edital, notice: 'Edital was successfully created.' }
        format.json { render :show, status: :created, location: @edital }
      else
        format.html { render :new }
        format.json { render json: @edital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editals/1
  # PATCH/PUT /editals/1.json
  def update
    respond_to do |format|
      if @edital.update(edital_params)
        format.html { redirect_to @edital, notice: 'Edital was successfully updated.' }
        format.json { render :show, status: :ok, location: @edital }
      else
        format.html { render :edit }
        format.json { render json: @edital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editals/1
  # DELETE /editals/1.json
  def destroy
    @edital.destroy
    respond_to do |format|
      format.html { redirect_to editals_url, notice: 'Edital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edital
      @edital = Edital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edital_params
      params.require(:edital).permit(:descricao, :habilitado)
    end
end

sigcopeinca/app/helpers/editals_helper.rb
module EditalsHelper
end

sigcopeinca/app/views/editals/_form.html.erb
<%= form_for(@edital) do |f| %>
  <% if @edital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edital.errors.count, "error") %> prohibited this edital from being saved:</h2>

      <ul>
      <% @edital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :habilitado %><br>
    <%= f.check_box :habilitado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sigcopeinca/app/views/editals/edit.html.erb
<h1>Editing edital</h1>

<%= render 'form' %>

<%= link_to 'Show', @edital %> |
<%= link_to 'Back', editals_path %>

sigcopeinca/app/views/editals/index.html.erb
<h1>Listing editals</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Habilitado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @editals.each do |edital| %>
      <tr>
        <td><%= edital.descricao %></td>
        <td><%= edital.habilitado %></td>
        <td><%= link_to 'Show', edital %></td>
        <td><%= link_to 'Edit', edit_edital_path(edital) %></td>
        <td><%= link_to 'Destroy', edital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Edital', new_edital_path %>

sigcopeinca/app/views/editals/new.html.erb
<h1>New edital</h1>

<%= render 'form' %>

<%= link_to 'Back', editals_path %>

sigcopeinca/app/views/editals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @edital.descricao %>
</p>

<p>
  <strong>Habilitado:</strong>
  <%= @edital.habilitado %>
</p>

<%= link_to 'Edit', edit_edital_path(@edital) %> |
<%= link_to 'Back', editals_path %>