sigcopeinca/config/routes.rb
Rails.application.routes.draw do
  resources :despachos

  resources :editals

  resources :alunos

  resources :servidors

end

sigcopeinca/app/models/despacho.rb
class Despacho < ActiveRecord::Base
  belongs_to :servidor
end

sigcopeinca/app/controllers/despachos_controller.rb
class DespachosController < ApplicationController
  before_action :set_despacho, only: [:show, :edit, :update, :destroy]

  # GET /despachos
  # GET /despachos.json
  def index
    @despachos = Despacho.all
  end

  # GET /despachos/1
  # GET /despachos/1.json
  def show
  end

  # GET /despachos/new
  def new
    @despacho = Despacho.new
  end

  # GET /despachos/1/edit
  def edit
  end

  # POST /despachos
  # POST /despachos.json
  def create
    @despacho = Despacho.new(despacho_params)

    respond_to do |format|
      if @despacho.save
        format.html { redirect_to @despacho, notice: 'Despacho was successfully created.' }
        format.json { render :show, status: :created, location: @despacho }
      else
        format.html { render :new }
        format.json { render json: @despacho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /despachos/1
  # PATCH/PUT /despachos/1.json
  def update
    respond_to do |format|
      if @despacho.update(despacho_params)
        format.html { redirect_to @despacho, notice: 'Despacho was successfully updated.' }
        format.json { render :show, status: :ok, location: @despacho }
      else
        format.html { render :edit }
        format.json { render json: @despacho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /despachos/1
  # DELETE /despachos/1.json
  def destroy
    @despacho.destroy
    respond_to do |format|
      format.html { redirect_to despachos_url, notice: 'Despacho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_despacho
      @despacho = Despacho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def despacho_params
      params.require(:despacho).permit(:data_inicio, :data_fim, :evento, :local, :passagem_aerea, :processo, :hora_inicio, :hora_fim, :servidor_id)
    end
end

sigcopeinca/app/helpers/despachos_helper.rb
module DespachosHelper
end

sigcopeinca/app/views/despachos/_form.html.erb
<%= form_for(@despacho) do |f| %>
  <% if @despacho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@despacho.errors.count, "error") %> prohibited this despacho from being saved:</h2>

      <ul>
      <% @despacho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_inicio %><br>
    <%= f.date_select :data_inicio %>
  </div>
  <div class="field">
    <%= f.label :data_fim %><br>
    <%= f.date_select :data_fim %>
  </div>
  <div class="field">
    <%= f.label :evento %><br>
    <%= f.text_field :evento %>
  </div>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :passagem_aerea %><br>
    <%= f.text_field :passagem_aerea %>
  </div>
  <div class="field">
    <%= f.label :processo %><br>
    <%= f.text_field :processo %>
  </div>
  <div class="field">
    <%= f.label :hora_inicio %><br>
    <%= f.text_field :hora_inicio %>
  </div>
  <div class="field">
    <%= f.label :hora_fim %><br>
    <%= f.text_field :hora_fim %>
  </div>
  <div class="field">
    <%= f.label :servidor_id %><br>
    <%= f.text_field :servidor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sigcopeinca/app/views/despachos/edit.html.erb
<h1>Editing despacho</h1>

<%= render 'form' %>

<%= link_to 'Show', @despacho %> |
<%= link_to 'Back', despachos_path %>

sigcopeinca/app/views/despachos/index.html.erb
<h1>Listing despachos</h1>

<table>
  <thead>
    <tr>
      <th>Data inicio</th>
      <th>Data fim</th>
      <th>Evento</th>
      <th>Local</th>
      <th>Passagem aerea</th>
      <th>Processo</th>
      <th>Hora inicio</th>
      <th>Hora fim</th>
      <th>Servidor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @despachos.each do |despacho| %>
      <tr>
        <td><%= despacho.data_inicio %></td>
        <td><%= despacho.data_fim %></td>
        <td><%= despacho.evento %></td>
        <td><%= despacho.local %></td>
        <td><%= despacho.passagem_aerea %></td>
        <td><%= despacho.processo %></td>
        <td><%= despacho.hora_inicio %></td>
        <td><%= despacho.hora_fim %></td>
        <td><%= despacho.servidor %></td>
        <td><%= link_to 'Show', despacho %></td>
        <td><%= link_to 'Edit', edit_despacho_path(despacho) %></td>
        <td><%= link_to 'Destroy', despacho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Despacho', new_despacho_path %>

sigcopeinca/app/views/despachos/new.html.erb
<h1>New despacho</h1>

<%= render 'form' %>

<%= link_to 'Back', despachos_path %>

sigcopeinca/app/views/despachos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data inicio:</strong>
  <%= @despacho.data_inicio %>
</p>

<p>
  <strong>Data fim:</strong>
  <%= @despacho.data_fim %>
</p>

<p>
  <strong>Evento:</strong>
  <%= @despacho.evento %>
</p>

<p>
  <strong>Local:</strong>
  <%= @despacho.local %>
</p>

<p>
  <strong>Passagem aerea:</strong>
  <%= @despacho.passagem_aerea %>
</p>

<p>
  <strong>Processo:</strong>
  <%= @despacho.processo %>
</p>

<p>
  <strong>Hora inicio:</strong>
  <%= @despacho.hora_inicio %>
</p>

<p>
  <strong>Hora fim:</strong>
  <%= @despacho.hora_fim %>
</p>

<p>
  <strong>Servidor:</strong>
  <%= @despacho.servidor %>
</p>

<%= link_to 'Edit', edit_despacho_path(@despacho) %> |
<%= link_to 'Back', despachos_path %>