sigcopeinca/config/routes.rb
Rails.application.routes.draw do
  resources :despachos

  resources :editals

  resources :alunos

  resources :servidors

end

sigcopeinca/app/models/servidor.rb
class Servidor < ActiveRecord::Base
end

sigcopeinca/app/controllers/servidors_controller.rb
class ServidorsController < ApplicationController
  before_action :set_servidor, only: [:show, :edit, :update, :destroy]

  # GET /servidors
  # GET /servidors.json
  def index
    @servidors = Servidor.all
  end

  # GET /servidors/1
  # GET /servidors/1.json
  def show
  end

  # GET /servidors/new
  def new
    @servidor = Servidor.new
  end

  # GET /servidors/1/edit
  def edit
  end

  # POST /servidors
  # POST /servidors.json
  def create
    @servidor = Servidor.new(servidor_params)

    respond_to do |format|
      if @servidor.save
        format.html { redirect_to @servidor, notice: 'Servidor was successfully created.' }
        format.json { render :show, status: :created, location: @servidor }
      else
        format.html { render :new }
        format.json { render json: @servidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servidors/1
  # PATCH/PUT /servidors/1.json
  def update
    respond_to do |format|
      if @servidor.update(servidor_params)
        format.html { redirect_to @servidor, notice: 'Servidor was successfully updated.' }
        format.json { render :show, status: :ok, location: @servidor }
      else
        format.html { render :edit }
        format.json { render json: @servidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servidors/1
  # DELETE /servidors/1.json
  def destroy
    @servidor.destroy
    respond_to do |format|
      format.html { redirect_to servidors_url, notice: 'Servidor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servidor
      @servidor = Servidor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servidor_params
      params.require(:servidor).permit(:siape, :nome, :email, :habilitado, :cpf, :lattes)
    end
end

sigcopeinca/app/helpers/servidors_helper.rb
module ServidorsHelper
end

sigcopeinca/app/views/servidors/_form.html.erb
<%= form_for(@servidor) do |f| %>
  <% if @servidor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servidor.errors.count, "error") %> prohibited this servidor from being saved:</h2>

      <ul>
      <% @servidor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :siape %><br>
    <%= f.text_field :siape %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :habilitado %><br>
    <%= f.check_box :habilitado %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :lattes %><br>
    <%= f.text_field :lattes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sigcopeinca/app/views/servidors/edit.html.erb
<h1>Editing servidor</h1>

<%= render 'form' %>

<%= link_to 'Show', @servidor %> |
<%= link_to 'Back', servidors_path %>

sigcopeinca/app/views/servidors/index.html.erb
<h1>Listing servidors</h1>

<table>
  <thead>
    <tr>
      <th>Siape</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Habilitado</th>
      <th>Cpf</th>
      <th>Lattes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servidors.each do |servidor| %>
      <tr>
        <td><%= servidor.siape %></td>
        <td><%= servidor.nome %></td>
        <td><%= servidor.email %></td>
        <td><%= servidor.habilitado %></td>
        <td><%= servidor.cpf %></td>
        <td><%= servidor.lattes %></td>
        <td><%= link_to 'Show', servidor %></td>
        <td><%= link_to 'Edit', edit_servidor_path(servidor) %></td>
        <td><%= link_to 'Destroy', servidor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Servidor', new_servidor_path %>

sigcopeinca/app/views/servidors/new.html.erb
<h1>New servidor</h1>

<%= render 'form' %>

<%= link_to 'Back', servidors_path %>

sigcopeinca/app/views/servidors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Siape:</strong>
  <%= @servidor.siape %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @servidor.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @servidor.email %>
</p>

<p>
  <strong>Habilitado:</strong>
  <%= @servidor.habilitado %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @servidor.cpf %>
</p>

<p>
  <strong>Lattes:</strong>
  <%= @servidor.lattes %>
</p>

<%= link_to 'Edit', edit_servidor_path(@servidor) %> |
<%= link_to 'Back', servidors_path %>